# Generated by Django 3.2.11 on 2022-01-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=50)),
                ('sensor_type', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
            ],
        ),
    ]
